steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_LOCATION-docker.pkg.dev/$PROJECT_ID/main-docker-repo/harmonization', '.' ]
images: ['$_LOCATION-docker.pkg.dev/$PROJECT_ID/main-docker-repo/harmonization']
substitutions:
  _LOCATION: northamerica-northeast1
options:
  logging: CLOUD_LOGGING_ONLY