steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/harmonization', '.' ]
images: ['gcr.io/$PROJECT_ID/harmonization']
substitutions:
  _LOCATION: northamerica-northeast1
options:
  logging: CLOUD_LOGGING_ONLY